apiVersion: v1
kind: Service
metadata:
  name: resource-processor
  namespace: course
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  type: NodePort
  selector:
    app: resource-processor