apiVersion: v1
kind: Service
metadata:
  name: storage-manager
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.storageManager.service.port }}
      targetPort: {{ .Values.storageManager.service.targetPort }}
  type: {{ .Values.storageManager.service.type }}
  selector:
    app: storage-manager