apiVersion: v1
kind: Service
metadata:
  name: resource-service-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.resourceServiceDb.service.port }}
      targetPort: {{ .Values.resourceServiceDb.service.port }}
  clusterIP: {{ .Values.resourceServiceDb.service.clusterIP }}
  selector:
    app: resource-service-db