apiVersion: v1
kind: Service
metadata:
  name: resource-service-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "resource-service-db-port"
      protocol: TCP
      port: {{ .Values.resourceServiceDb.service.port }}
      targetPort: {{ .Values.resourceServiceDb.service.targetPort }}
  type: {{ .Values.resourceServiceDb.service.clusterIP }}
  selector:
    app: resource-service-db