apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: 9092