apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "zookeeper-port"
      port: {{ .Values.zookeeper.service.port }}
      targetPort: {{ .Values.zookeeper.service.targetPort }}
  type: {{ .Values.zookeeper.service.type }}
  selector:
    app: zookeeper