apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: course
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  type: NodePort
  selector:
    app: elasticsearch