apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.7.0
          envFrom:
            - configMapRef:
                name: elasticsearch-config
          ports:
            - containerPort: 9200
              protocol: TCP
