apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.authorizationService.service.type }}
  selector:
    app: authorization-service
  ports:
    - protocol: TCP
      port: {{ .Values.authorizationService.service.port }}
      targetPort: {{ .Values.authorizationService.service.port }}