apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: course
spec:
  ports:
    - name: "4566"
      port: 4566
      targetPort: 4566
  type: NodePort
  selector:
    app: localstack