apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          ports:
            - containerPort: 4566
              protocol: TCP
