apiVersion: v1
kind: Service
metadata:
  name: storage-manager
  namespace: course
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  type: NodePort
  selector:
    app: storage-manager