apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: {{ .Values.namespace }}
  labels:
    date: {{ include "chart.labels.currentDate" . }}
    version: {{ include "chart.labels.version" . }}
spec:
  replicas: {{ .Values.localstack.replicaCount }}
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: "{{ .Values.localstack.image.repository }}:{{ .Values.localstack.image.tag }}"
          imagePullPolicy: {{ .Values.authorizationService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.localstack.service.targetPort }}
              protocol: TCP
