apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.localstack.service.port }}
      targetPort: {{ .Values.localstack.service.targetPort }}
  type: {{ .Values.localstack.service.type }}
  selector:
    app: localstack