apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: song-service
  namespace: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
        - name: song-service
          image: song-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              protocol: TCP
          envFrom:
            - configMapRef:
                name: song-service-config
            - secretRef:
                name: song-service-secret
          volumeMounts:
            - mountPath: /log
              name: logs
      restartPolicy: "Always"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logstash-pvc