apiVersion: v1
kind: Secret
metadata:
  name: song-service-secret
  namespace: course
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vc29uZy1zZXJ2aWNlLWRiOjU0MzIvc29uZw==
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: MTIzNDU2Nzg=