apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: course
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  type: NodePort
  selector:
    app: song-service