apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.logstash.service.port }}
      targetPort: {{ .Values.logstash.service.targetPort }}
  type: {{ .Values.logstash.service.type }}
  selector:
    app: logstash