apiVersion: v1
kind: Service
metadata:
  name: storage-manager-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "storage-manager-db-port"
      protocol: TCP
      port: {{ .Values.storageManagerDb.service.port }}
      targetPort: {{ .Values.storageManagerDb.service.targetPort }}
  type: {{ .Values.storageManagerDb.service.clusterIP }}
  selector:
    app: storage-manager-db