apiVersion: v1
kind: Service
metadata:
  name: storage-manager-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.storageManagerDb.service.port }}
  clusterIP: {{ .Values.storageManagerDb.service.clusterIP }}
  selector:
    app: storage-manager-db