apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.7.0
          envFrom:
            - configMapRef:
                name: kibana-config
          ports:
            - containerPort: 5601
              protocol: TCP