apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
  labels:
    date: {{ include "chart.labels.currentDate" . }}
    version: {{ include "chart.labels.version" . }}
spec:
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: {{ .Values.kafka.service.port }}