apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.port }}
  type: {{ .Values.kafka.service.type }}
  selector:
    app: kafka