apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{ .Values.namespace }}
data:
  KAFKA_PORT: "9092"
  KAFKA_ADVERTISED_HOST_NAME: kafka
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

