apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-volume
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /Users/Siarhei_Viarbouski/microservices/Resource service/docker/logstash/log