apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-gateway-service
  namespace: course
spec:
  type: NodePort
  selector:
    app: spring-cloud-gateway-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084