apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-manager-db
  namespace: course
spec:
  serviceName: "storage-manager-db"
  replicas: 1
  selector:
    matchLabels:
      app: storage-manager-db
  template:
    metadata:
      labels:
        app: storage-manager-db
    spec:
      containers:
        - name: storage-manager-db
          image: postgres:14-alpine3.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: storage-manager-db-secret
