apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: course
spec:
  type: NodePort
  selector:
    app: authorization-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
