apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.songService.service.port }}
      targetPort: {{ .Values.songService.service.port }}
  type: {{ .Values.songService.service.type }}
  selector:
    app: song-service