apiVersion: v1
kind: ConfigMap
metadata:
  name: song-service-config
  namespace: {{ .Values.namespace }}
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  eureka.client.serviceUrl.defaultZone: http://service-discovery:8761/eureka
