apiVersion: v1
kind: Service
metadata:
  name: service-configuration
  namespace: course
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  type: NodePort
  selector:
    app: service-configuration