apiVersion: v1
kind: Service
metadata:
  name: resource-service-db
  namespace: course
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: resource-service-db