apiVersion: v1
kind: Service
metadata:
  name: resource-processor
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.resourceProcessor.service.port }}
      targetPort: {{ .Values.resourceProcessor.service.targetPort }}
  type: {{ .Values.resourceProcessor.service.type }}
  selector:
    app: resource-processor