apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "service-discovery-port"
      port: {{ .Values.serviceDiscovery.service.port }}
      targetPort: {{ .Values.serviceDiscovery.service.targetPort }}
  type: {{ .Values.serviceDiscovery.service.type }}
  selector:
    app: service-discovery