apiVersion: v1
kind: Service
metadata:
  name: song-service-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.songServiceDb.service.port }}
  clusterIP: {{ .Values.songServiceDb.service.clusterIP }}
  selector:
    app: song-service-db