apiVersion: v1
kind: Secret
metadata:
  name: song-service-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_DB: c29uZw==
  POSTGRES_USERNAME: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIzNDU2Nzg=