apiVersion: v1
kind: Service
metadata:
  name: song-service-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "song-service-db-port"
      protocol: TCP
      port: {{ .Values.songServiceDb.service.port }}
      targetPort: {{ .Values.songServiceDb.service.targetPort }}
  type: {{ .Values.songServiceDb.service.clusterIP }}
  selector:
    app: song-service-db