apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:8.7.0
          ports:
            - containerPort: 9600
              protocol: TCP
          volumeMounts:
            - name: logstash-config-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
              readOnly: true
            - mountPath: /var/lib/docker/logstash/logs
              name: logs
              readOnly: true
          command: ["/usr/share/logstash/bin/logstash", "-f", "/usr/share/logstash/pipeline/logstash.conf"]
      restartPolicy: Always
      volumes:
        - name: logstash-config-volume
          configMap:
            name: logstash-config
        - name: logs
          hostPath:
            path: /Users/Siarhei_Viarbouski/microservices/Resource service/docker/logstash/log