apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: course
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  type: NodePort
  selector:
    app: resource-service